### ISSUE TITLE
Use OpenDP to implement repeated, simulated noise

### ISSUE THREAD

**Issue by nvembar** [crisisready/DP_Metapopulation#1]
Using the [OpenDP](https://github.com/opendp) libraries, implement a pipeline that ingests the data from Camber that will feed into the metapopulation model and generate many different versions of that output with noise added, a la the [Microsoft paper](https://drive.google.com/drive/folders/1FZxDcU0-ZdHAXqVzCibnCbf2OrizCRxZ) on validating the use of DP. The noise-applied data should be parametrizable with different epsilon values so that utility/privacy tradeoffs can be assessed.

If feasible, directly integrate with the ingestion pipeline in R using the OpenDP hooks so we have a single codebase. Otherwise, create and document a Python pipeline that runs along side the R code.

**Comment by SaviKoissi** [comment]
It is possible to use python code and packages in the R environment, I will try with the library and get back to you.
