### ISSUE TITLE
# Line 39: 

### ISSUE THREAD

**Issue by SaviKoissi** [crisisready/DP_Metapopulation#9]
https://github.com/crisisready/DP_Metapopulation/blob/0c9db779a5eda25ec66d5996d900ccabbc1adc76/src/camber_etl.R#L39

This line of code resort this error 
 Error: Problem with `summarise()` input `Count`.
x object 'Count' not found
i Input `Count` is `sum(Count, na.rm = TRUE)`.
i The error occurred in group 1: from_fips = "36001", to_fips = "36001".

**Comment by SaviKoissi** [comment]
I do not quite understand the error since with 
rescaled_data%>%
  #group_by(from_fips, to_fips)%>%
  filter (from_fips == 36001)%>%
  filter (to_fips == 36001) 

You can observe that transitions is different from na

**Comment by nish-kishore** [comment]
I think this is resolved in the latest branch. Once you review and update could you check again? If it works could you close this issue out? @SaviKoissi
